gdtools_rest_projects:
    type: rest
    resource: 'ApiBundle\Controller\ProjectController'
    name_prefix: api_

gdtools_rest_decks:
    type: rest
    resource: 'ApiBundle\Controller\DeckController'
    name_prefix: api_
