services:
    api.request_service:
        class: ApiBundle\Services\RequestService
        arguments: [ "@doctrine.orm.entity_manager", "@form.factory", "@service_container" ]

    api.form.project_type:
        class: ApiBundle\Form\Type\ProjectType
        tags:
            - { name: form.type }

    api.entity.project:
        class: ApiBundle\Entity\Project